image: alpine/edge
secrets:
  - e592e466-8d8b-4b07-b13f-2ca1e50b1720
sources:
  - git@git.sr.ht/~iameyad/advent-of-code-2025
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      echo 'cd advent-of-code-2025' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:IAmEyad/advent-of-code-2025.git
